### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by fxgenstudio** [EnthusiastGuy/MonoGame-Pixel-Planets#1]
Please use nuget to reference monogame.

C:\Downloaded\MonoGame-Pixel-Planets\MonoPixelPlanets.csproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Also, tried to find "MonoGame\v3.0\MonoGame.Content.Builder.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\jnada\AppData\Local\Microsoft\VisualStudio\16.0_5a094979\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Downloaded\MonoGame-Pixel-Planets\MonoPixelPlanets.csproj

**Comment by EnthusiastGuy** [comment]
Thanks for the heads up, I'll take a look at this and get back to you.

**Comment by fxgenstudio** [comment]
Thanks a lot. It's very nice as projet 🙂
I'll try to add a planet as background for my game.

________________________________
De : Enthusiast Guy <notifications@github.com>
Envoyé : samedi 6 mars 2021 21:59
À : EnthusiastGuy/MonoGame-Pixel-Planets <MonoGame-Pixel-Planets@noreply.github.com>
Cc : procfxgen <jnadalutti@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [EnthusiastGuy/MonoGame-Pixel-Planets] Can't open project (#1)


Thanks for the heads up, I'll take a look at this and get back to you.

**Comment by EnthusiastGuy** [comment]
Ok, I believe I've done something different than you did.
What I just tried was to download the project on a different laptop where it wasn't ran on before and try to run it there.
It did took a minute to download/build packages, also because it's an old laptop, but for me it works from the first try.

You also made a suggestion over using nuget to reference monogame. I believe it's there, I clearly see it in the project references.

What did you do? Maybe I'm coming at this from a bad angle?

**Comment by fxgenstudio** [comment]
I found why... I used vs2019 monogame v3.8 extension and not monogame 3.7.


https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_windows.html

**Comment by fxgenstudio** [comment]
We could migrate to 3.8 ?

https://docs.monogame.net/articles/migrate_37.html

**Comment by EnthusiastGuy** [comment]
Hmm, then I may not have the correct templates. Weird, I installed 3.8 a while ago.
I now see I am using version 3.7.1.189, so that's not right.
I did had a bit of trouble with the templates. Will check and see if I can reinstall.

**Comment by EnthusiastGuy** [comment]
Done migrating. Should be fine now, but let me know if there are any issues.

**Comment by fxgenstudio** [comment]
That work fine ! Thanks.
